""" 
Version 4: Make Set iterable by providing *__iter__*
which returns an iterator.  The best iterator is a lazy, on-demand iterator
generated by a generator function.

After making Set iterable, we can say 

  for x in self

instead of

  for x in self.rep

"""

def iterator(s):
        for x in s.rep:
                yield x

def new(C, *args, **kw):
        return C(*args, **kw)

class Set:

        def intersection(self, other):
                s = new(type(self))
                for x in self:
                        if x in other:
                                s.add(x)
                return s

        def __iter__(self):
                return iterator(self)

class DictSet(Set):
        def __init__(self,elements=()):
                rep = self.rep= {}
                for element in elements:
                        rep[element] = element

        def add(self, x):
                self.rep[x] = x

class ListSet(Set):
        def __init__(self,elements=()):
                rep = self.rep = []
                for element in elements:
                        if element not in rep:
                                rep.append(element)

        def add(self, x):
                self.rep.append(x)


s = DictSet([1,2,3,4])
t = DictSet([3,4,5,6])
r = s.intersection(t)
print(r.rep)
u = ListSet([1,2,3,4])
v = ListSet([3,4,5,6])
w = u.intersection(v)
print(w.rep)
        
